fix: fixed parsing for node
stacktracejs/error-stack-parser pull request #66
Opened 2021-10-07 10:36 UTC by Aleksey28

## Description
1. added pre-replace unnecessary part of the line instead of slicing it after splitting
2. fixed removing last round bracket during throwing out eval information
3. removed regexp group ':(\d+):(\d+)' because we should get any location in brackets
4. removed splitting 'sanitizedLine' and reorganized using 'sanitizedLine' and 'location'
5. added a new option for node error test when the function name isn't there

## Motivation and Context

I have a problem with the Node.js product. In some ways error looks like this:
```
Error
    at /var/app/scratch/my project/index.js:2:9
    at Object.<anonymous> (/var/app/scratch/my project/index.js:2:9)
    at Module._compile (internal/modules/cjs/loader.js:774:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
    at Module.load (internal/modules/cjs/loader.js:641:32)
    at Function.Module._load (internal/modules/cjs/loader.js:556:12)
    at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
    at internal/main/run_main_module.js:17:11
```
First-line doesn't have a function name and round brackets and it loses full file name after splitting.

## How Has This Been Tested?

Added new option for test 'should handle spaces in Node.js stacks'

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:

- [ ] `node_modules/.bin/jscs -c .jscsrc error-stack-parser.js` passes without errors
- [x] `npm test` passes without errors
- [x] I have read the [contribution guidelines](CONTRIBUTING.md)
- [ ] I have updated the documentation accordingly
- [x] I have added tests to cover my changes

2022-01-17 23:41 UTC, niftylettuce commented
@Aleksey28 I wanted to follow up - I haven't had a chance to closely review this - but I would love to merge.  Is this ready to go?  I see you haven't checked off two checkboxes in the checklist above (docs and running that script without errors).

2022-01-17 23:42 UTC, niftylettuce requested changes
See my comment (you didn't check off two checkboxes yet in the GH issue template).

2022-02-02 09:07 UTC, Aleksey28 commented
@niftylettuce Yes, it's ready to go. I haven't checked because they're unnecessary and they just were in the template of the PR. I think it outdated checkboxes

- node_modules/.bin/jscs -c .jscsrc error-stack-parser.js passes without errors - I think it's outdated checkbox. The project now has ESLint instead of this package and also the project doesn't have this package in dependencies
- I have updated the documentation accordingly - my bugfix doesn't need any documentation updates

2022-02-02 15:41 UTC, merged

2022-02-02 15:47 UTC, niftylettuce commented
Ping @eriwen for npm owner access so I can publish v2.0.7 via `np`

2022-02-11 17:45 UTC, niftylettuce commented
v2.0.7 published, thanks again @eriwen 🙏  cc @Aleksey28 

https://github.com/stacktracejs/error-stack-parser/releases/tag/v2.0.7